apiVersion: v1

kind: Pod

metadata:

  name: nginx

  labels:
    type: statefulset
    app: ai

spec:

  containers:

  - name: nginx

    image: centos/systemd 

    volumeMounts:

    - mountPath: "/tmp"

      name: myvolume

  volumes:

  - name: myvolume

    persistentVolumeClaim:

      claimName: iscsipvc
