apiVersion: v1

kind: PersistentVolume

metadata:

  name: iscsi-pv1

spec:

  capacity:

    storage: 100Mi

  accessModes:

  - ReadWriteOnce

  iscsi:

    targetPortal: 192.168.1.12:3260

    iqn: iqn.1992-04.com.emc:storage.sudhakaran.lvmdisk

    lun: 0

    fsType: ext4

    readOnly: false
